# Generated by Django 4.0.1 on 2022-02-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuser',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='nuser',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='nuser',
            name='MartialStatus',
        ),
    ]
