# Generated by Django 4.0.1 on 2022-02-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0002_remove_nuser_age_remove_nuser_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuser',
            name='Role',
        ),
    ]
