# Generated by Django 4.0.2 on 2022-02-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0004_nuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Stamp', models.CharField(max_length=50)),
                ('Direction', models.CharField(max_length=50)),
                ('Source', models.CharField(max_length=50)),
                ('Destination', models.CharField(max_length=50)),
                ('MessageId', models.CharField(max_length=50)),
                ('Length', models.CharField(max_length=50)),
                ('StatusTx', models.CharField(max_length=50)),
                ('Data', models.CharField(max_length=50)),
            ],
        ),
    ]
