# Generated by Django 4.0.1 on 2022-04-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0006_myuploadfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuploadfile',
            name='myfiles',
        ),
    ]
