# Generated by Django 4.0.1 on 2022-04-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0007_remove_myuploadfile_myfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuploadfile',
            name='myfiles',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
