# Generated by Django 4.0.1 on 2022-04-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0008_myuploadfile_myfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myuploadfile',
            new_name='myuploadfiles',
        ),
    ]
