# Generated by Django 4.0.1 on 2022-04-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0010_myuploadfile_delete_myuploadfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='myuploadfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('myfiles', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='myuploadfile',
        ),
    ]
