# Generated by Django 4.0.1 on 2022-04-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0011_myuploadfiles_delete_myuploadfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myuploadfiles',
            new_name='myuploadfiless',
        ),
    ]
