# Generated by Django 4.0.1 on 2022-04-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0013_myuploadfile_delete_myuploadfiless'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuploadfile',
            name='f_name',
        ),
    ]
