# Generated by Django 4.0.1 on 2022-04-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0014_remove_myuploadfile_f_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuploadfile',
            old_name='myfiles',
            new_name='myfile',
        ),
    ]
