# Generated by Django 4.0.1 on 2022-04-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0016_tablecsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='Date',
            field=models.CharField(max_length=50),
        ),
    ]
