# Generated by Django 4.0.1 on 2022-04-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0017_alter_table_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='tablecsvs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
