# Generated by Django 3.2.6 on 2022-07-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0020_csvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='file_encoded',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='file',
            field=models.FileField(db_column='data', upload_to='files/'),
        ),
    ]
