# Generated by Django 3.2.6 on 2022-07-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0022_auto_20220718_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=255, null=True)),
                ('mois', models.CharField(max_length=255, null=True)),
                ('jour', models.CharField(max_length=255, null=True)),
                ('file', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
