# Generated by Django 3.2.6 on 2022-07-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0023_rapport'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='heure',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='minute',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='second',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
