# Generated by Django 3.2.6 on 2022-07-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0024_auto_20220730_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='photosaver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(max_length=255, null=True)),
                ('image', models.BinaryField(blank=True, editable=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rapport',
            name='file',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
