# Generated by Django 3.2.6 on 2022-07-31 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0025_auto_20220731_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photosaver',
            old_name='id_user',
            new_name='user',
        ),
    ]
