# Generated by Django 3.2.6 on 2022-07-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0026_rename_id_user_photosaver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosaver',
            name='image',
            field=models.TextField(),
        ),
    ]
