# Generated by Django 3.2.6 on 2022-07-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0027_alter_photosaver_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='file',
            field=models.TextField(),
        ),
    ]
