# Generated by Django 3.2.6 on 2022-07-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0028_alter_rapport_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosaver',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='file',
            field=models.TextField(blank=True),
        ),
    ]
